<#import "parts/common.ftlh" as c/>


<style>
    *{
        color: #16cb68
    }
</style>

<@c.basic>

    <div class="container d-flex flex-column
                justify-content-center align-items-center h-50">
        <div class="text-center">
            <h3>Ви завітали на сторінку гуртожитку №1</h3>
            <span>Розпорядок роботи: 8-00 - 20-00</span>
        </div>
    </div>


</@c.basic>
